import React from 'react'
import { useNavigate } from 'react-router-dom'

const LazyLoading = () => {
    const navigate = useNavigate()
  return (
    <div>
           <button onClick={()=>navigate(-1)}>Back</button>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a tellus a tortor convallis pulvinar sit amet at lacus. Aliquam mauris metus, congue sed accumsan a, vestibulum posuere nunc. Proin vestibulum, turpis quis aliquet bibendum, erat diam pulvinar sem, quis iaculis lectus augue quis sapien. Sed id nisi lorem. Fusce pretium pharetra tortor in varius. In nec euismod nunc, quis dignissim dolor. Suspendisse finibus eros quam, at malesuada justo tristique eget. Mauris ac enim vel ante pharetra ultrices. Integer tincidunt sollicitudin pellentesque. Integer non arcu eu risus rutrum accumsan. Nam vel est in tellus fermentum pharetra et sed sapien. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
Etiam nec turpis ultricies, feugiat dui sed, placerat elit. Nullam sem justo, gravida ut cursus vitae, pretium sit amet ante. Phasellus sed dui in ante commodo iaculis et nec enim. Aenean et semper dui. Duis pulvinar quam non ligula fermentum, vitae placerat leo porttitor. Aenean turpis metus, facilisis nec auctor ac, feugiat id lectus. Nunc in tellus mattis, imperdiet erat eget, mattis justo. In volutpat tellus a mauris dignissim lobortis. In elementum, tortor et faucibus blandit, sapien nisl laoreet mi, non faucibus lacus eros volutpat arcu. In eu nibh sollicitudin augue auctor finibus. Vestibulum ac est velit. Maecenas sit amet tristique ex. Curabitur libero sem, finibus et lacinia vel, consequat quis mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris id diam a arcu posuere lobortis vel maximus sapien.
Aenean ac nunc sem. Nam pharetra imperdiet augue elementum posuere. Donec dui sapien, cursus ac erat sed, viverra accumsan arcu. Donec vestibulum quis elit ac molestie. Nunc nec eros quis erat finibus sollicitudin vel et nisl. Duis non pharetra dolor, non commodo nisl. In hac habitasse platea dictumst. Aenean blandit vestibulum nunc, ac pulvinar velit fringilla ac. Sed in magna rutrum, semper ligula id, egestas velit. Curabitur semper semper consequat.
Cras scelerisque erat in ligula tempor venenatis et vel justo. Curabitur sit amet massa eu neque blandit vestibulum id id sapien. Suspendisse sit amet feugiat erat, quis vestibulum est. Etiam ac placerat nisl, eget vestibulum nisl. Nam eros purus, finibus quis tortor vitae, ultrices maximus massa. Duis metus quam, ullamcorper id lacinia ut, luctus in leo. Etiam faucibus fringilla quam. Proin condimentum mollis euismod. Aenean eu iaculis mi. Morbi eleifend consectetur dolor in vestibulum.
Praesent sed dictum enim. Morbi molestie tempor nibh, vel mattis elit condimentum sit amet. Cras facilisis mauris quis viverra mattis. Fusce euismod augue nibh, ac efficitur quam vulputate id. Sed in justo consequat, posuere sem eget, sagittis urna. Pellentesque commodo luctus efficitur. Nunc vestibulum, tortor et consectetur luctus, nibh leo commodo mauris, at finibus justo lorem ut ipsum. Vivamus non leo at libero feugiat ornare a in nisi. Morbi ante urna, mattis sed diam eu, laoreet scelerisque velit. Ut commodo consequat erat, at venenatis diam egestas at.
Aliquam erat volutpat. Etiam ac gravida leo, eu lobortis ipsum. Sed dui velit, consequat eget risus at, pharetra ullamcorper elit. Aliquam id vehicula ipsum. Etiam et odio eu arcu vehicula ultricies ac laoreet velit. Aenean maximus libero quis mauris porttitor faucibus. Aenean ullamcorper finibus nibh, non varius ex feugiat at. Ut massa mi, facilisis eget efficitur id, porttitor non ipsum. Nam nunc nulla, ultrices vel tincidunt vel, iaculis sed orci. Suspendisse et est at velit sagittis auctor. Suspendisse varius tempor lorem, nec maximus libero porttitor nec.
Nunc non dignissim lorem. Nunc sit amet faucibus diam, vel iaculis est. In hac habitasse platea dictumst. Duis cursus augue lobortis iaculis facilisis. Integer tempus orci vel lacus gravida consectetur. Aliquam ut condimentum nisi. Integer velit massa, fermentum eu arcu nec, consectetur cursus erat. Integer tristique cursus mattis. Aliquam venenatis sodales ligula, ac sollicitudin libero auctor sit amet.
Mauris ullamcorper, ex ut mollis congue, tortor augue aliquet diam, a vulputate metus sem eu felis. Donec vehicula elit elit. Donec vel semper dui. Proin vulputate, velit et sagittis sollicitudin, neque quam porta orci, et tristique felis urna ac leo. Fusce condimentum urna nisi, ut fermentum libero facilisis et. Aenean sit amet feugiat velit. Nullam quis lacinia mi. Praesent congue porta ante eu finibus. Duis ac nulla lorem. Praesent sem magna, tristique aliquam est sed, varius cursus nunc.
Etiam id elementum nulla. Fusce elementum, diam ut eleifend scelerisque, sapien augue pretium risus, eget ultricies dolor nunc ac mi. Curabitur commodo aliquet erat, ut hendrerit metus vestibulum vitae. Donec laoreet condimentum risus id suscipit. Donec molestie tellus sit amet neque placerat, id mattis eros facilisis. Etiam eros libero, congue et posuere ac, tempor eu metus. Nam sit amet maximus sem. Donec arcu mi, fermentum in commodo ac, consectetur ut felis. Sed fermentum eleifend urna in consectetur. Proin et efficitur massa. Proin sit amet massa viverra, facilisis urna ac, mollis massa.
Sed vel volutpat risus. Mauris lobortis a dolor id ultricies. Maecenas vehicula ex eros, id convallis lorem venenatis dictum. Aliquam ligula sapien, euismod in vestibulum vitae, auctor aliquet mi. In hac habitasse platea dictumst. Duis tincidunt ligula turpis, at accumsan dui ultricies a. Donec arcu mauris, vehicula in auctor et, ullamcorper vel ipsum. Nam faucibus velit et pellentesque viverra. In rhoncus scelerisque magna, eget condimentum leo porttitor et. Aliquam efficitur urna sed diam maximus, sit amet volutpat nibh blandit. Integer rutrum est at orci commodo, in tristique massa aliquet. Duis ac nisi libero. Nunc bibendum, arcu ac scelerisque ornare, ligula quam sodales ligula, non facilisis tellus felis sed lacus. Aliquam erat volutpat. Sed a porttitor urna, vitae imperdiet nisi.
Vestibulum eget fermentum neque, id convallis urna. Quisque leo ligula, vehicula id purus a, maximus dignissim nulla. Phasellus ac dapibus nunc, ac eleifend nunc. Phasellus tincidunt mauris quis ornare varius. Ut vitae malesuada erat. Duis nec scelerisque nulla. Vivamus hendrerit ante vel lectus eleifend porta. Maecenas ut turpis a lectus cursus euismod ac quis risus. In nec justo arcu. Nullam semper justo tellus, in vulputate lectus fermentum non. In vitae convallis dui, in placerat felis. Sed fermentum nibh sed erat ullamcorper aliquet. Suspendisse aliquet nec velit ac euismod.
Sed gravida, enim ut mattis facilisis, enim sem ultrices odio, vel tristique velit libero quis purus. Phasellus magna orci, fermentum eget blandit quis, tincidunt sed lectus. Vivamus in convallis nisi. Nunc in ante lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi non urna diam. Integer eu euismod mauris, id pulvinar mauris. Vestibulum volutpat magna et lectus facilisis, vitae congue nulla elementum. Duis sollicitudin tempor ante at molestie. Maecenas vehicula, ligula vitae consectetur laoreet, ligula ipsum aliquam lectus, nec porttitor mi ipsum cursus enim. Nulla euismod metus et commodo gravida. In nisi ex, porta quis tortor hendrerit, vestibulum dignissim ex. Quisque ut placerat eros, vel condimentum enim. Curabitur ornare mi quis aliquet cursus. Nunc blandit, tellus eget tristique mollis, felis nunc convallis lacus, vel rutrum lectus lorem vitae nunc.
Nullam eget diam dui. Phasellus in est eros. Donec egestas nibh et magna fringilla, non posuere neque ornare. Maecenas at venenatis eros. Integer condimentum turpis in dolor viverra dapibus. Quisque viverra eget lectus ut euismod. Ut sed elit quis felis varius sodales.
Nunc ac aliquam tellus. Ut at leo mattis, posuere ipsum ac, auctor ligula. Vestibulum tempor mauris finibus scelerisque sagittis. Integer eget dui malesuada, tincidunt dui vitae, feugiat nunc. Praesent a euismod tellus. In ac feugiat dolor. Praesent at sollicitudin leo. In cursus risus ut nulla faucibus condimentum. Vestibulum vitae scelerisque est, in fermentum quam. Sed semper rutrum nibh, in pulvinar lacus efficitur vel. Aenean ullamcorper ultrices tincidunt. Pellentesque at odio risus.
Aenean nec turpis suscipit, pharetra urna at, ullamcorper nisl. Aenean tempor, nibh ac rhoncus dictum, lacus nulla pretium mauris, vel lacinia nisl sem non nisi. Phasellus facilisis faucibus interdum. Aliquam eget libero ultrices, faucibus nibh sit amet, ultricies ante. Fusce dolor lectus, mattis quis suscipit ut, sodales sit amet purus. Suspendisse hendrerit sagittis arcu in semper. Nunc bibendum ipsum purus, vitae vehicula magna ultrices et. Nulla lacinia pretium aliquet. Nulla mollis pellentesque mauris, sed ornare ex facilisis eu. Mauris a vestibulum libero. Pellentesque sodales eros ipsum, et pharetra magna imperdiet ut. Nam lorem metus, ullamcorper ac accumsan id, accumsan eget urna. Nunc commodo lectus nisl, non interdum ipsum mollis vitae. Sed dapibus, nisi nec consectetur pharetra, elit neque vestibulum mi, in volutpat orci elit ac nulla. Suspendisse et lorem eu velit ultrices eleifend sed eu odio. Cras semper efficitur lacus, id elementum ipsum ullamcorper ac.
Cras laoreet, magna non aliquam sodales, urna felis aliquam felis, ut scelerisque magna tellus eu orci. Integer bibendum tortor eu consequat consectetur. Curabitur non laoreet lorem, ac faucibus diam. In mattis cursus posuere. Aliquam ut urna nunc. Aliquam ac augue ex. Suspendisse purus magna, malesuada id placerat at, commodo ultrices diam. Morbi placerat malesuada nisi, a egestas ex rutrum id. Aliquam malesuada lacinia neque luctus hendrerit. Vivamus pretium justo et ante feugiat, eget tincidunt tellus molestie. Quisque commodo orci libero, non maximus risus tincidunt quis. Duis est diam, blandit sit amet ipsum at, posuere commodo lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce fermentum porta elit, nec faucibus elit imperdiet sed. Aliquam erat volutpat.
Etiam sit amet velit sed sapien cursus eleifend quis eget libero. Donec a risus eu dui cursus porta sed sit amet justo. Sed aliquam pellentesque orci ut maximus. Sed a ante ultrices, hendrerit sem a, laoreet elit. Suspendisse at lectus ut dui elementum convallis vitae eget risus. Quisque tempus, orci vel varius tempor, sem mi faucibus lacus, efficitur lobortis augue mi ac massa. Ut in finibus metus.
Cras sagittis diam nunc, sit amet rhoncus urna maximus non. Quisque vel rutrum purus. Mauris mattis feugiat augue eu sagittis. Suspendisse sagittis odio mi, non auctor nibh tempor vitae. Praesent pellentesque sapien quis felis placerat pulvinar ut at ligula. Suspendisse potenti. Nunc cursus mollis elit id volutpat. Sed quam massa, porta et augue in, suscipit semper nisl. Phasellus condimentum sed erat non rhoncus. Integer id orci nec orci posuere lacinia nec ornare massa. Nulla a justo accumsan, molestie massa non, lacinia lectus. Vivamus vitae consectetur risus, ac lacinia magna. Praesent gravida velit ac pretium bibendum. Phasellus massa leo, pretium quis neque eget, dapibus maximus sapien. Etiam tristique, quam ut bibendum dapibus, leo risus condimentum metus, in elementum dolor augue varius lorem.
Curabitur consequat lorem sed dignissim pellentesque. Mauris commodo dolor eget est dapibus condimentum. Pellentesque at aliquet nisl. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vitae eleifend risus, eget sodales lorem. Mauris mi est, lacinia ut sem sed, rutrum rhoncus magna. Aliquam quis purus et justo placerat tempus. Vivamus sed enim metus. Fusce et lacus faucibus, faucibus ante porttitor, ultrices est. Maecenas imperdiet suscipit nisl, eu feugiat erat. Phasellus gravida est vestibulum blandit aliquet. Etiam vel odio eu magna varius aliquet. Aliquam erat volutpat. Quisque tincidunt volutpat ante at pellentesque. Integer eros lorem, bibendum eget convallis vel, eleifend sed arcu.
Quisque felis diam, dictum in risus at, bibendum molestie nibh. Maecenas dignissim, neque eu feugiat facilisis, est velit ornare ipsum, vitae finibus risus nulla at lacus. Nullam rutrum bibendum nibh, vitae viverra ligula luctus nec. Proin quis iaculis ante, id semper lorem. Mauris eget lorem ac elit sagittis gravida. In tincidunt vestibulum egestas. Nullam semper facilisis urna ac posuere. Praesent et lorem nec ipsum aliquam dignissim.</p>
    </div>
  )
}

export default LazyLoading